### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nsturm** [ItsEcholot/node-red-contrib-snmp-trap-listener#1]
When i am trying to install it, i get the following error: 

verbose stack Error: Command failed: git submodule -q update --init --recursive
verbose stack fatal: unable to connect to github.com:
verbose stack github.com[0: 192.30.253.112]: errno=Connection timed out
verbose stack github.com[1: 192.30.253.113]: errno=Connection timed out
verbose stack
verbose stack Clone of 'git://github.com/davepacheco/javascriptlint.git' into submodule path 'deps/javascriptlint' failed
verbose stack
verbose stack     at ChildProcess.exithandler (child_process.js:199:12)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at ChildProcess.emit (events.js:191:7)
verbose stack     at maybeClose (internal/child_process.js:920:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
verbose cwd /data
error Linux 4.4.0-119-generic
error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-snmp-trap-listener"
error node v6.13.1
error npm  v3.10.10
error code 1
error Command failed: git submodule -q update --init --recursive
error fatal: unable to connect to github.com:
error github.com[0: 192.30.253.112]: errno=Connection timed out
error github.com[1: 192.30.253.113]: errno=Connection timed out
error
error Clone of 'git://github.com/davepacheco/javascriptlint.git' into submodule path 'deps/javascriptlint' failed
error If you need help, you may report this error at:
error     <https://github.com/npm/npm/issues>
verbose exit [ 1, true ]

On my client node-red is running in a docker container, where other addons were installed successfully. For me it seems that the problem it trys a "git" connection and not "http" connection to the special submodul.

Does anyone else has similar problems?

Thanks

**Comment by ItsEcholot** [comment]
Is git installed in your docker container? It is needed to resolve the submodules.

**Comment by nsturm** [comment]
Yes it is. It is installed and found under /usr/bin which is also in the environment path. 
For this example i use the docker which comes directly from node-red (https://nodered.org/docs/platforms/docker) - Perhaps you can comprehend the problem with this docker file.

**Comment by nsturm** [comment]
I think i found the problem. The installation tries to download also the following git repository ("github.com/davepacheco/javascriptlint.git") which did not exists anymore ! 

Clone of 'git://github.com/davepacheco/javascriptlint.git' into submodule path 'deps/javascriptlint' failed

But i have no solution?

**Comment by ItsEcholot** [comment]
I just tried installing the npm package on my desktop without any issues. It seems your environment is somehow causing this and not my package. Because of this I will be closing this issue.
The owner of the package javascriptlint has changed but a redirect has been made by github so this shouldn't cause it.
