### ISSUE TITLE
node-red restarting after installation of snmp-trap-listener

### ISSUE THREAD

**Issue by cawGitHub** [ItsEcholot/node-red-contrib-snmp-trap-listener#11]
Hi
after the installation of this package node.red ist going into a bootloop with the following messages:

```
6 May 21:23:20 - [info] Flows gestartet
6 May 21:23:20 - [red] Uncaught Exception:
6 May 21:23:20 - Error: bind EACCES 0.0.0.0:162
    at dgram.js:339:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 24.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
6 May 21:23:22 - [info]
Willkommen bei Node-RED!
===================
6 May 21:23:22 - [info] Node-RED Version: v1.0.6
6 May 21:23:22 - [info] Node.js  Version: v12.16.3
6 May 21:23:22 - [info] Linux 4.19.97-v7+ arm LE
6 May 21:23:23 - [info] Paletten-Nodes werden geladen
```

**Comment by ItsEcholot** [comment]
Please take a look at #4 and #9

**Comment by Ekristoffe** [comment]
hint you don't have the right to open those port with the default user.
ps I am still looking how to catch this error and keep node-red alive. 
any idea?

**Comment by ItsEcholot** [comment]
> hint you don't have the right to open those port with the default user.
> ps I am still looking how to catch this error and keep node-red alive.
> any idea?

Yeah maybe try wrapping the
```
        trapd.bind({family: 'udp4', port: parseInt(config.port)}, () => {
            console.log(moment().format(logTimeFormat) + `Success binding to port ${config.port} and listening for traps`);
            node.status({fill: 'green', shape: 'dot', text: 'ready'});
        });
``` 
in a try & catch

**Comment by Ekristoffe** [comment]
already tried and try catch doesn't work for function with callback (asynchro) since we will be out of the try before the real test is done ...

**Comment by ItsEcholot** [comment]
Maybe the `bind` function returns an error object to the callback. For further discussion for an updated version and for things which isn't related to this issue, send me an email so we don't spam the GitHub issues 👍
