### ISSUE TITLE
The snmp-trap-listener (for node red) fails with error - port unavailable, need assistance

### ISSUE THREAD

**Issue by dachshund-digital** [ItsEcholot/node-red-contrib-snmp-trap-listener#14]
The snmp-trap-listener (for node red) fails with error - port unavailable, need assistance.  I have index.js running via node console, but the node does not seem to be able to connect to it?

`$ sudo node index.js
3 Aug 23:53:14 - [log] Debug options: {"fill":"yellow","shape":"ring","text":"connecting"}
3 Aug 23:53:14 - [log] Listening for traps on port: 162
3 Aug 23:53:14 - [log] Debug options: {"fill":"green","shape":"dot","text":"ready"}
3 Aug 23:53:14 - [log] Bound to RED event: close
3 Aug 23:53:14 - [log] Would execute: function() {
                        // Cleanup before node is being deleted.
                        node.log("Closing port: " + config.port);
                        node.status({fill: "gray", shape: "ring", text: "offline"});
                        node.receiver.close();
                }
`

It does appear the process is listening on 162?
` $ sudo netstat -nlpu|grep 162
udp        0      0 0.0.0.0:162             0.0.0.0:*                           15610/node
`

**Comment by ItsEcholot** [comment]
Is this related to #15 and fixed with the latest npm release?

**Comment by dachshund-digital** [comment]
At the time I opened the two different issues, I did not believe they were related.  But when I test, I will confirm everything is working as expected.  That Node Red sees the service, and the service receives a trap without crashing.

**Comment by Nodi-Rubrum** [comment]
You may find this interesting, and for others that find this thread, you do not need to setup port forwarding to use this node under node-red running under a non-root id. Here is the procedure to use a non-privileged port, example below port 10162:

1) Under net-snmp5, edit /etc/snmp/snmpd.conf. Change the trap authorizations to qualify : syntax:
`
#--------------------------------------------------------------------------------
\# SNMPv1 traps
\#trapsink localhost public 162
trapsink localhost:10162 public

\# SNMPv2c traps
\#trap2sink localhost publicl 162
trap2sink localhost:10162 public

\# SNMPv2c INFORMs
\#informsink localhost public 162
informsink localhost:10162 public
#--------------------------------------------------------------------------------`

2) Restart the snmpd and snmptrapd services.

\# systemctl restart snmpd
\# systemctl status snmpd
\# systemctl restart snmptrapd
\# systemctl status snmptrapd

3) Validate that port 10162 is used.
    `root@[]:# systemctl restart snmpd
    root@[]:# systemctl status snmpd
    ● snmpd.service - Simple Network Management Protocol (SNMP) Daemon.
    Loaded: loaded (/lib/systemd/system/snmpd.service; enabled; vendor preset: enabled)
    Active: active (running) since Thu 2020-08-13 02:55:23 UTC; 6s ago
    Process: 25131 ExecStartPre=/bin/mkdir -p /var/run/agentx (code=exited, status=0/SUCCESS)
    Main PID: 25132 (snmpd)
    Tasks: 1 (limit: 4915)
    CGroup: /system.slice/snmpd.service
    └─25132 /usr/sbin/snmpd -LS6d -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -f -p /run/snmpd.pid

Aug 13 02:55:23 pi4modelb0.dachshund-digital.org systemd[1]: Starting Simple Network Management Protocol (SNMP) Daemon....
Aug 13 02:55:23 [] systemd[1]: Started Simple Network Management Protocol (SNMP) Daemon..
Aug 13 02:55:23 [] snmpd[25132]: Turning on AgentX master support.
Aug 13 02:55:23 [] snmpd[25132]: NET-SNMP version 5.7.3
`
4) Add snmp trap listener node to a Node Red flow. The node should change to a ready status if it is able to monitor the 10162 port.  Check the network port binding.

    \# netstat -tulp | grep 10162 udp 0 0 0.0.0.0:10162 0.0.0.0:* 6663/node-red

5) Send snmp test trap. Note that host name includes the reassigned port number of 10162.

\#  snmptrap -v 2c -c public localhost:10162 '' NET-SNMP-EXAMPLES-MIB::netSnmpExampleHeartbeatNotification netSnmpExampleHeartbeatRate i 88888888

6) Look in the Node Red editor, the snmp trap listener node (say connected to a debug node) should have display in the debug window, the trap generated and received.
    8/12/2020, 8:01:30 PMnode: Message msg : Object object payload: array[3] 0: object oid: "1.3.6.1.2.1.1.3.0" typename: "TimeTicks" value: 24657880 string_value: "24657880" 1: object oid: "1.3.6.1.6.3.1.1.4.1.0" typename: "OID" value: "1.3.6.1.4.1.8072.2.3.0.1" string_value: "1.3.6.1.4.1.8072.2.3.0.1" 2: object oid: "1.3.6.1.4.1.8072.2.3.2.1" typename: "Integer" value: 88888888 string_value: "88888888" src: object family: "IPv4" address: "192.168.1.100" port: 41554 version: 1 string_version: "TrapV2" _msgid: "45fabb90.e09944"

Enjoy!
