### ISSUE TITLE
When trap listener receives the following test trap, it crashes with the following error

### ISSUE THREAD

**Issue by dachshund-digital** [ItsEcholot/node-red-contrib-snmp-trap-listener#15]
Running node index.js per the instructions...  at a console window...
`$ sudo node index.js
4 Aug 01:18:38 - [log] Debug options: {"fill":"yellow","shape":"ring","text":"connecting"}
4 Aug 01:18:38 - [log] Listening for traps on port: 162
4 Aug 01:18:38 - [log] Debug options: {"fill":"green","shape":"dot","text":"ready"}
4 Aug 01:18:38 - [log] Bound to RED event: close
4 Aug 01:18:38 - [log] Would execute: function() {
                        // Cleanup before node is being deleted.
                        node.log("Closing port: " + config.port);
                        node.status({fill: "gray", shape: "ring", text: "offline"});
                        node.receiver.close();
                }
`

From a remote device, if I send the following snmp trap...
`sudo snmptrap -v 1 -c xxxxxxxxxxxxxxxx 127.0.0.1 .1.3.6.1.6.3 "" 0 0 sysName.0`

The listener crashes...
/home/pi/.node-red/node_modules/node-red-contrib-snmp-trap-listener/snmp-trap-listener.js:93
                                node.debug("Received: " + JSON.stringify(trap));
                                     ^

TypeError: node.debug is not a function
    at Receiver.callback (/home/pi/.node-red/node_modules/node-red-contrib-snmp-trap-listener/snmp-trap-listener.js:93:10)
    at Receiver.onMsg (/home/pi/.node-red/node_modules/net-snmp/index.js:2842:8)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8)

This can't possibly be the expected result.   Also the original issue I posted is still true, I cannot get the node in the wire-editor to see the trap service at all.  So this solution is broken in at least two different ways, based on the testing I have done so far.

**Comment by ItsEcholot** [comment]
I forgot to publish the latest version (2.1.0) to npm. This has been done now. Please check again with the newest version.

**Comment by dachshund-digital** [comment]
Did you update the git repo?  None of the files seem to show updated time/date info?

**Comment by ItsEcholot** [comment]
No, the Repo was ahead of the NPM release. Now they're both on the same version

**Comment by dachshund-digital** [comment]
Cool will test again.  Thanks

**Comment by dachshund-digital** [comment]
Ok, running index.js from trap listener directory, And a flow setup in node-red, so the listener node can output to the debug console.  Here is what I notice.

1) I never see the 'status' state from the trap listener node watching the flow. So 'Debug options: {"fill":"green","shape":"dot","text":"ready"}" I see in the log, but not in the node red wire editor view.

2) When I send a trap, this now what results...
/home/pi/.node-red/node_modules/node-red-contrib-snmp-trap-listener/snmp-trap-listener.js:93
                                node.debug("Received: " + JSON.stringify(trap));
                                     ^

TypeError: node.debug is not a function
    at Receiver.callback (/home/pi/.node-red/node_modules/node-red-contrib-snmp-trap-listener/snmp-trap-listener.js:93:10)
    at Receiver.onMsg (/home/pi/.node-red/node_modules/node-red-contrib-snmp-trap-listener/node_modules/net-snmp/index.js:2842:8)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:910:8)

I removed the library and reloaded it using npm uninstall and npm install.  So I believe i have the latest library version?

**Comment by ItsEcholot** [comment]
I don't quite grasp what your setup exactly is. This is supposed to be run inside of node-red, and only for developing / debugging purposes directly using node.

To check which version is installed check the package.json inside of the downloaded version.

**Comment by Nodi-Rubrum** [comment]
Pulling down the latest via npm install, the package file shows...
"node-red-contrib-snmp-trap-listener": "~2.0.0",

$ npm install node-red-contrib-snmp-trap-listener
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-contrib-snmp-trap-listener@2.0.0
updated 1 package and audited 795 packages in 11.748s

44 packages are looking for funding
  run `npm fund` for details

found 159 vulnerabilities (48 low, 62 moderate, 49 high)
  run `npm audit fix` to fix them, or `npm audit` for details

I have several devices, in my home lab, that generate SNMP traps and I would like to capture them in Node Red.  I think my use case is pretty straight forward.  I have extensive experience with SNMP, I have design enterprise monitoring solutions for 100K server infrastructure sites. I mention this only so that you will know I have detailed understanding of SNMP and its proper use.

As far as testing, I am following your read me/usage instructions, I believe correctly.  I start the index.js via node, start node-red-log on a separate console, activate a flow that uses your node in Node Red. Then on yet another console, I send a simple SNMP trap.  Your index.js script receives the trap but then generates the documented error.  The Node Red node every shows any status change, as the trap is received.  Nor does the Node Red node show it is seeing the index.js script (listener) running.  So there are two issues here, 1) You listener crashes, 2) the Node Red node fails to receive/show anything. Likely the 2 issues are related of course.

**Comment by Nodi-Rubrum** [comment]
I noticed something... npm @latest pulled a different version of your module.  That should not be happening, in the default npm install method should do that as well.  You still have not prompted the github repository to 2.1.0?

Now when I run index.js, it aborts directly with the following error...
 $ node index.js
10 Aug 01:46:41 - [log] Debug options: {"fill":"yellow","shape":"ring","text":"connecting"}
10 Aug 01:46:41 - [log] Listening for traps on port: 162
10 Aug 01:46:41 - [log] Adding Community: tip
10 Aug 01:46:41 - [log] Adding Community: tap
10 Aug 01:46:41 - [log] Adding Community: top
10 Aug 01:46:41 - [log] Debug options: {"fill":"green","shape":"dot","text":"ready"}
10 Aug 01:46:41 - [log] Bound to RED event: close
10 Aug 01:46:41 - [log] Would execute: function() {
                        // Cleanup before node is being deleted.
                        node.log("Closing port: " + config.port);
                        node.status({fill: "gray", shape: "ring", text: "offline"});
                        node.receiver.close();
                }
10 Aug 01:46:41 - [log] Oops: {"errno":"EACCES","code":"EACCES","syscall":"bind","address":"0.0.0.0","port":162}
10 Aug 01:46:41 - [log] can't open port: 162
10 Aug 01:46:41 - [log] Debug options: {"fill":"red","shape":"dot","text":"error - port unavailable"}

Requires sudo?

$ sudo node index.js
10 Aug 01:48:17 - [log] Debug options: {"fill":"yellow","shape":"ring","text":"connecting"}
10 Aug 01:48:17 - [log] Listening for traps on port: 162
10 Aug 01:48:17 - [log] Adding Community: tip
10 Aug 01:48:17 - [log] Adding Community: tap
10 Aug 01:48:17 - [log] Adding Community: top
10 Aug 01:48:17 - [log] Debug options: {"fill":"green","shape":"dot","text":"ready"}
10 Aug 01:48:17 - [log] Bound to RED event: close
10 Aug 01:48:17 - [log] Would execute: function() {
                        // Cleanup before node is being deleted.
                        node.log("Closing port: " + config.port);
                        node.status({fill: "gray", shape: "ring", text: "offline"});
                        node.receiver.close();
                }
10 Aug 01:51:24 - [log] Received: {"pdu":{"type":164,"enterprise":"1.3.6.1.6.3","agentAddr":"192.168.1.100","generic":0,"specific":0,"upTime":0,"varbinds":[],"scoped":false},"rinfo":{"address":"127.0.0.1","family":"IPv4","port":43841,"size":49}}
10 Aug 01:51:24 - [log] Debug options: {"fill":"blue","shape":"dot","text":"ready - trapped"}
10 Aug 01:51:24 - [log] Received Trap from 127.0.0.1: 1.3.6.1.6.3
10 Aug 01:51:24 - [log] Would send: {"payload":[],"enterprise":"1.3.6.1.6.3","agent_addr":"192.168.1.100","generic_trap":0,"specific_trap":0,"time_stamp":0,"src":{"family":"IPv4","address":"127.0.0.1","port":43841},"version":0,"string_version":"Trap"}
10 Aug 01:51:25 - [log] Debug options: {"fill":"green","shape":"dot","text":"ready"}

Well, a bit of progress with 2.1.0 version.  The index.js script did not crash when trap received.  But... the node in Node Red, never see it, Node Red node still reports ERROR - port unavailable, even though the receiver script is running.

8/9/2020, 6:56:33 PMnode: 45e90a76.b65094
msg : string[20]
"can't open port: 162"

**Comment by ItsEcholot** [comment]
First off, your version, as you've noticed is outdated. The version on GitHub, has nothing to do with the version published on npm and which you download with `npm install node-red-contrib-snmp-trap-listener`. 
The current published version on npm is 2.1.0, if your npm installs a different version, there's an issue at your end (cache or something else).

Second, this npm module is a node-red node. It is to be run **only** inside node-red in production. The `node index.js` method is **only** for development / debugging. It seems you are starting it outside of node-red (using `node index.js`) **and** inside of node-red. This is wrong.
Simply add the node to the palette and then the node to a flow. For this to work on the default SNMP port, you have to start node-red as root. Alternatively for a safer solution take a look at #4 on how to proxy the port to a higher one which doesn't need higher privileges.

**Comment by Nodi-Rubrum** [comment]
Only ran index.js to confirm that the port was open, since the node reported the port was not open.  I don't recall the comment about running NR as root in your documentation, but now that you call it out, makes sense.  Of course, shifting the port to higher assignment, has its own pros and cons of course, but I digress.

**Comment by Nodi-Rubrum** [comment]
You may find this interesting, and for others that find this thread, you do not need to setup port forwarding to use this node under node-red running under a non-root id. Here is the procedure to use a non-privileged port, example below port 10162:

1) Under net-snmp5, edit /etc/snmp/snmpd.conf. Change the trap authorizations to qualify : syntax:
`
#--------------------------------------------------------------------------------
\# SNMPv1 traps
\#trapsink localhost public 162
trapsink localhost:10162 public

\# SNMPv2c traps
\#trap2sink localhost publicl 162
trap2sink localhost:10162 public

\# SNMPv2c INFORMs
\#informsink localhost public 162
informsink localhost:10162 public
#--------------------------------------------------------------------------------`

2) Restart the snmpd and snmptrapd services.

\# systemctl restart snmpd
\# systemctl status snmpd
\# systemctl restart snmptrapd
\# systemctl status snmptrapd

3) Validate that port 10162 is used.
    `root@[]:# systemctl restart snmpd
    root@[]:# systemctl status snmpd
    ● snmpd.service - Simple Network Management Protocol (SNMP) Daemon.
    Loaded: loaded (/lib/systemd/system/snmpd.service; enabled; vendor preset: enabled)
    Active: active (running) since Thu 2020-08-13 02:55:23 UTC; 6s ago
    Process: 25131 ExecStartPre=/bin/mkdir -p /var/run/agentx (code=exited, status=0/SUCCESS)
    Main PID: 25132 (snmpd)
    Tasks: 1 (limit: 4915)
    CGroup: /system.slice/snmpd.service
    └─25132 /usr/sbin/snmpd -LS6d -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -f -p /run/snmpd.pid

Aug 13 02:55:23 pi4modelb0.dachshund-digital.org systemd[1]: Starting Simple Network Management Protocol (SNMP) Daemon....
Aug 13 02:55:23 [] systemd[1]: Started Simple Network Management Protocol (SNMP) Daemon..
Aug 13 02:55:23 [] snmpd[25132]: Turning on AgentX master support.
Aug 13 02:55:23 [] snmpd[25132]: NET-SNMP version 5.7.3
`
4) Add snmp trap listener node to a Node Red flow. The node should change to a ready status if it is able to monitor the 10162 port.  Check the network port binding.

    \# netstat -tulp | grep 10162 udp 0 0 0.0.0.0:10162 0.0.0.0:* 6663/node-red

5) Send snmp test trap. Note that host name includes the reassigned port number of 10162.

\#  snmptrap -v 2c -c public localhost:10162 '' NET-SNMP-EXAMPLES-MIB::netSnmpExampleHeartbeatNotification netSnmpExampleHeartbeatRate i 88888888

6) Look in the Node Red editor, the snmp trap listener node (say connected to a debug node) should have display in the debug window, the trap generated and received.
    8/12/2020, 8:01:30 PMnode: Message msg : Object object payload: array[3] 0: object oid: "1.3.6.1.2.1.1.3.0" typename: "TimeTicks" value: 24657880 string_value: "24657880" 1: object oid: "1.3.6.1.6.3.1.1.4.1.0" typename: "OID" value: "1.3.6.1.4.1.8072.2.3.0.1" string_value: "1.3.6.1.4.1.8072.2.3.0.1" 2: object oid: "1.3.6.1.4.1.8072.2.3.2.1" typename: "Integer" value: 88888888 string_value: "88888888" src: object family: "IPv4" address: "192.168.1.100" port: 41554 version: 1 string_version: "TrapV2" _msgid: "45fabb90.e09944"

Enjoy!

**Comment by ItsEcholot** [comment]
Thanks for another way to circumvent the port issue!

In that case I assume that this issue is resolved, and will go ahead and close it.

**Comment by Nodi-Rubrum** [comment]
Yeah... Much easier and cleaner way to do it.  I was really happy when I found it actually worked too!  Thanks for being proactive on the issues as well.  Always nice when authors are actively engaged.
