### ISSUE TITLE
 Packets from Type InformRequests are not recognized

### ISSUE THREAD

**Issue by Sven0507** [ItsEcholot/node-red-contrib-snmp-trap-listener#16]
Hello,

when I send packets from Type InformRequests, they are not recognized.

Thanks

**Comment by Ekristoffe** [comment]
hello do you have the packet ? 
i would like to do some test with the same packet

**Comment by Sven0507** [comment]
Hi, thanks for your reply.
I have the packet as a buffer, does it help you?

`[48,129,194,2,1,1,4,6,112,117,98,108,105,99,166,129,180,2,4,28,165,202,196,2,1,0,2,1,0,48,129,165,48,15,6,8,43,6,1,2,1,1,3,0,67,3,9,133,197,48,26,6,10,43,6,1,6,3,1,1,4,1,0,6,12,43,6,1,4,1,130,252,49,1,100,3,13,48,45,6,12,43,6,1,4,1,130,252,49,1,1,5,0,4,29,50,48,50,48,45,49,48,45,51,48,84,49,48,58,50,56,58,53,53,46,55,56,50,43,48,49,58,48,48,48,19,6,14,43,6,1,4,1,130,252,49,1,3,1,1,4,0,2,1,4,48,29,6,14,43,6,1,4,1,130,252,49,1,3,1,2,4,0,4,11,40,57,41,32,82,75,32,84,195,188,114,48,19,6,14,43,6,1,4,1,130,252,49,1,3,1,13,4,0,2,1,0]`

**Comment by Ekristoffe** [comment]
should be solved when #18 will be publish in npm (and node-red)

**Comment by ItsEcholot** [comment]
Version 2.4.0 is live on npm and should solve your issue, thanks @Ekristoffe for providing the pull request #18

**Comment by Ekristoffe** [comment]
@Sven0507 just in case please give it a try and give us a feedback :)

**Comment by Sven0507** [comment]
Thank you, works exactly as it should. 😀
