### ISSUE TITLE
crashes when SNMPv3 trap string has no data

### ISSUE THREAD

**Issue by Easyfilecopy** [ItsEcholot/node-red-contrib-snmp-trap-listener#19]
crashes when SNMPv3 trap string has no data

with wireshark and send data center expert snmp trap, we could see a snmp trap without 
                        1.3.6.1.4.1.5528.100.11.8: <MISSING>
                        1.3.6.1.4.1.5528.100.11.9: <MISSING>

This is okay when uses SNMPv1.
But SNMPv3, it stops at net-snmp. I will try to report to net-snmp.

workaround fix:

.node-red\node_modules\net-snmp\index.js

				case ObjectType.OctetString:
					if (typeof value == "string")
						buffer.writeString (value);
					else
						//buffer.writeBuffer (value, ObjectType.OctetString);
                                                buffer.writeString ("");
					break;

**Comment by ItsEcholot** [comment]
I'm sorry but I currently don't have time to test and fix this issue. But feel free to submit a PR with a fix.

**Comment by Easyfilecopy** [comment]
Hi, Marc.

This is not problem about node-red-contrib-snmp-trap-listener.

I've report to NET-SNMP maintainer. NET-SNMP maintainer knows this and will fix it.

I just write this for someone may use SNMPv3 and Data Center Expert. They could do a workaround fix.

Thanks for your good node-red-contrib-snmp-trap-listener.

**Comment by ItsEcholot** [comment]
Thanks, in that case I will close this issue.
