### ISSUE TITLE
Help for using this tool

### ISSUE THREAD

**Issue by diegoflyer** [ItsEcholot/node-red-contrib-snmp-trap-listener#22]
Dear!
I am really new on this and I am trying to using snmp trap on node red.
My snmp trap sender is working correctly (checked with an another receiver) but I have no data received on my flow.
![image](https://user-images.githubusercontent.com/46562259/216185826-0e8dda7e-bde6-47be-b122-27fdbf228d1d.png)
Here my flow, I checked also on netstat and no services are running on udp port 162.
Any suggestion?
Thanks in advance

**Comment by acedog5** [comment]
I am having the same problem, did you find a solution to the problem?

**Comment by diegoflyer** [comment]
Yes I had that working @acedog5 I will try to answer this evening when at home, if I forgot please send me a "trap"

**Comment by acedog5** [comment]
Thanks I appreciate it, I found something about changing the port number to get around the error, but I'm interested in your solution!


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by acedog5** [comment]
@diegoflyer what was your solution?

**Comment by diegoflyer** [comment]
Sorry @acedog5 but I had some busy days....
I remembered that there was a problem with the port privilege and I solved the problem by following instruction:
https://discourse.nodered.org/t/problems-to-open-port-162-snmp-trap/31555
At the end I changed the privilege for non-root user in some way, did you find a similar solution?

**Comment by acedog5** [comment]
I was able to bypass the problem by changing the port number > 1024 then using the firewall to remap 162 port to 16200. 
@diegoflyer  Thanks for your reply.

**Comment by ItsEcholot** [comment]
Glad you guys figured out a solution! This is basically the same issue as described in #4. Sadly on Linux there isn't an easy way around this issue without some manual intervention / workarounds.

Since this seems resolved for now I'm gonna close this issue. Feel free to re-open if this isn't the case.
