### ISSUE TITLE
no way to differentiate between source IP.

### ISSUE THREAD

**Issue by AndKe** [ItsEcholot/node-red-contrib-snmp-trap-listener#23]
the documentation suggests there is a src field with IP address.
this is what I see:

![image](https://github.com/ItsEcholot/node-red-contrib-snmp-trap-listener/assets/1468842/c60c83db-5647-48ef-a06c-907d2f9a5ed7)

Filtering by IP and adding more than one nodes does not seem to work as the first instance "eats" the packet.

Please add source IP data.

**Comment by annuello** [comment]
I think you're only looking at msg.payload.  Change your debug node to show the whole message, and you'll find msg.src contains the IPv4 source address.

**Comment by AndKe** [comment]
@annuello Thank you!  - this works perfectly fine.
