### ISSUE TITLE
Missing trap sender IP address

### ISSUE THREAD

**Issue by djok** [ItsEcholot/node-red-contrib-snmp-trap-listener#5]
Great work,

In case multiple devices send same traps to trap listener there is no way to know from where trap comes.

msg should contain trap source IP address.

**Comment by ItsEcholot** [comment]
That makes sense... Would love to accept a pull request for this feature. If not I would be willing to look into this myself but can't guarantee a timeframe.

**Comment by djok** [comment]
btw, agent address is not a part of the payload, but exist in msg.agent_addr.

**Comment by Ekristoffe** [comment]
hello you have access to the sender ip address at `msg.src.address`.

**Comment by ItsEcholot** [comment]
Yes as @Ekristoffe mentioned this is now solved in v2
