### ISSUE TITLE
Crashes on deploy?

### ISSUE THREAD

**Issue by mikemelga** [ItsEcholot/node-red-contrib-snmp-trap-listener#9]
Hi.

I wanted to manage some SNMP devices and this plugin looks like what I need.
I installed it on my nodered docker. 
However...when I add it and make a simple flow (just the trap listener and a debug output) i crashes when I deploy.
I configure the trap listener, setting the port (162), comunity (private), ip (192.168.0.251) and netmask (24). It always crashes the entire docker which remains in a boot loop until I delete the flows.json file (or replace with an earlier version).

Am I doing something wrong?

Thanks.

**Comment by ItsEcholot** [comment]
I suspect this is because of Permission problems check out the following information already provided for this issue:
- https://github.com/ItsEcholot/node-red-contrib-snmp-trap-listener/pull/7#issuecomment-578591020
- #4 

If this doesn't help you fix your problem I will need the generated logs to help you further.

**Comment by mikemelga** [comment]
Hi.
Thanks for the reply.
Indeed it was a permissions issue.
As soon as I used a higher port number it worked.

Thanks!

**Comment by mikemelga** [comment]
Hi again.

Now I don't have a permissions issue but I don't receive any trap  :(

I tried using port 162 and other higher ports (4000) and I don't receive any trap :(
I tried a trap receiver program for testing and it receives ok. I even made a short VB app to test sending and nothing arrives (but arrives on the test program).
Tried my APC PDU to send traps... still nothing.

I tried running the docker as root... still nothing.
Mapped the ports to the host... still nothing.

I am missing something. But what?
Any ideas?

Thanks again.

**Comment by Ekristoffe** [comment]
it seem you are in docker.
Please take care to see if your docker can receive broadcast or multicast frame.

**Comment by Ekristoffe** [comment]
update in docker the simples way is to use another port inside the node-red configuration and link this container port to the port 162.
Example: 
the command,
```
docker run -d --name node-red --restart always -p 1880:1880 -v node_red_user_data:/data -v node_red_user_datacgroup:/sys/fs/cgroup nodered/node-red:latest
```
will become,
```
docker run -d --name node-red --restart always -p 1880:1880 -p 162:1162 -v node_red_user_data:/data -v node_red_user_datacgroup:/sys/fs/cgroup nodered/node-red:latest
```
and in the node-red configuration use the port 1162.
(you can also bind the port 161 of the machine to 1161 in the container)

**Comment by ItsEcholot** [comment]
Thanks for this tip @Ekristoffe I added it to the pinned issue #4 👍
